### ISSUE TITLE
Node V12

### ISSUE THREAD

**Issue by staifan** [atom/node-spellchecker#119]
Hello,
I have not found a problem with node JS version 12 so in case you have not had the information, the installation of the Spellchecker module on windows 10 with node V12 does not seem to work.
Installing your module gives:

> C:\Users\Stef\nodeTest>npm install spellchecker --save
> spellchecker@3.5.3 install C:\Users\Stef\nodeTest\node_modules\spellchecker
> node-gyp rebuild
C:\Users\Stef\nodeTest\node_modules\spellchecker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\Stef\nodeTest\node_modules\spellchecker\build\..\vendor\hunspell\src\hunspell\utf_info.hxx
Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  affentry.cxx
  affixmgr.cxx
  csutil.cxx
  dictmgr.cxx
  filemgr.cxx
  hashmgr.cxx
  hunspell.cxx
  hunzip.cxx
  phonet.cxx
  replist.cxx
  suggestmgr.cxx
  textparser.cxx
  win_delay_load_hook.cc
  hunspell.vcxproj -> C:\Users\Stef\nodeTest\node_modules\spellchecker\build\Release\\hunspell.lib
  main.cc
  worker.cc
  spellchecker_hunspell.cc
  spellchecker_win.cc
  transcoder_win.cc
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(74): error C2660: 'v8::String::Write' : la fonction ne prend pas 1 arguments [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(2732): note: voir la déclaration de 'v8::String::Write' (compilation du fichier source ..\src\main.cc)
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(85): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3358): note: voir la déclaration de 'v8::Object::Set'
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(86): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3358): note: voir la déclaration de 'v8::Object::Set'
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(87): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3367): note: voir la déclaration de 'v8::Object::Set'
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(105): error C2660: 'v8::String::Write' : la fonction ne prend pas 1 arguments [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(2732): note: voir la déclaration de 'v8::String::Write' (compilation du fichier source ..\src\main.cc)
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(156): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3367): note: voir la déclaration de 'v8::Object::Set'
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(179): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3367): note: voir la déclaration de 'v8::Object::Set'
c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(210): error C2660: 'v8::FunctionTemplate::GetFunction' : la fonction ne prend pas 0 arguments [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(5947): note: voir la déclaration de 'v8::FunctionTemplate::GetFunction' (compilation du fichier source ..\src\main.cc)
c:\users\stef\nodetest\node_modules\spellchecker\src\worker.cc(38): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3358): note: voir la déclaration de 'v8::Object::Set'c:\users\stef\nodetest\node_modules\spellchecker\src\main.cc(210): error C2661: 'v8::Object::Set' : aucune fonction surchargée ne nécessite 1 arguments
c:\users\stef\nodetest\node_modules\spellchecker\src\worker.cc(39): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3358): note: voir la déclaration de 'v8::Object::Set' win_delay_load_hook.cc
c:\users\stef\nodetest\node_modules\spellchecker\src\worker.cc(40): warning C4996: 'v8::Object::Set': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\.node-gyp\12.0.0\include\node\v8.h(3367): note: voir la déclaration de 'v8::Object::Set'
c:\users\stef\nodetest\node_modules\spellchecker\src\worker.cc(44): warning C4996: 'Nan::Callback::Call': a été déclaré déconseillé [C:\Users\Stef\nodeTest\node_modules\spellchecker\build\spellchecker.vcxproj]
c:\users\stef\nodetest\node_modules\nan\nan.h(1674): note: voir la déclaration de 'Nan::Callback::Call'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Stef\nodeTest\node_modules\spellchecker
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN nodeTest@1.0.0 No description
npm WARN nodeTest@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spellchecker@3.5.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@3.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stef\AppData\Roaming\npm-cache\_logs\2019-05-07T14_03_01_690Z-debug.log

**Comment by rsese** [comment]
> so in case you have not had the information, 

Thanks for the heads up!  Issues with Node v12 seem to be known I think, see https://github.com/atom/node-spellchecker/pull/108#issuecomment-487529798.

**Comment by staifan** [comment]
Version 3.6.0 works perfectly on node V12 and therefore on Electron 5.XX
thank you
