### ISSUE TITLE
Cannot open include file: 'spellcheck.h': (Windows)

### ISSUE THREAD

**Issue by MBeckers** [atom/node-spellchecker#12]
Inspellchecker_win.cc is the line "#include <spellcheck.h>"
but nowhere i can find spellcheck.h

  spellchecker_win.cc
..\src\spellchecker_win.cc(7): fatal error C1083: Cannot open include file: 'spellcheck.h': No such file or directory [C:\atom\node_modules\spellchec
ker\build\spellchecker.vcxproj]
..\src\main.cc(109): warning C4996: 'NanSymbol': was declared deprecated [C:\atom\node_modules\spellchecker\build\spellchecker.vcxproj]
          C:\atom\node_modules\spellchecker\node_modules\nan\nan.h(395) : see declaration of 'NanSymbol'
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\atom\node_modules\spellchecker
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "spellchec
ker"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! spellchecker@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellchecker@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the spellchecker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls spellchecker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\atom\npm-debug.log

**Comment by paulcbetts** [comment]
You probably don't have the Windows 8+ SDK installed, this API is new to Windows 8
