### ISSUE TITLE
v3.6.0 package contains ~175 MB of .vscode files

### ISSUE THREAD

**Issue by javan** [atom/node-spellchecker#123]
I upgraded an electron app from v3.5.3 to v3.6.0 and the build size jumped significantly. Tracked the extra weight back to https://unpkg.com/spellchecker@3.6.0/.vscode/
<pre>
$ pwd
/tmp/test/node_modules/spellchecker

$ du -hc . | grep M
1.2M	./build/Release/obj.target/spellchecker/src
1.2M	./build/Release/obj.target/spellchecker
2.1M	./build/Release/obj.target
3.4M	./build/Release
3.5M	./build
 83M	./.vscode/ipch/7f56f8a8ad139ab6
 83M	./.vscode/ipch/e0f6371f7634001f
166M	./.vscode/ipch
166M	./.vscode
1.1M	./vendor/hunspell/src/hunspell
1.2M	./vendor/hunspell/src
1.3M	./vendor/hunspell
2.0M	./vendor
172M	.
172M	total
</pre>

**Comment by rafeca** [comment]
Thanks for the heads up @javan 😅

I'll republish a new version without that folder

**Comment by rafeca** [comment]
Published v3.6.1 without the `.vscode` files, thanks for creating the issue!
