### ISSUE TITLE
Find words that start with

### ISSUE THREAD

**Issue by blainesch** [atom/node-spellchecker#14]
It would be nice if I could find words that start with a given string. For instance typing in "energ" might give me "energy".

**Comment by lee-dohm** [comment]
Is this for spell-checking? Or are you looking for more of an auto-complete sort of thing?

**Comment by blainesch** [comment]
For an auto-complete feature, so it's likely out of scope.

**Comment by lee-dohm** [comment]
You might want to take a look at the [autocomplete-plus package](https://atom.io/packages/autocomplete-plus) and see if they have something that will cover what you're looking for. Let me know if I can help! :grinning:
