### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed. on Windows

### ISSUE THREAD

**Issue by abnerlee** [atom/node-spellchecker#18]
I used to use spellchecker with electron on Windows 8 successfully, but after I upgrade io.js to v2.3.1, electron (electron-prebuilt) to v0.29.2, spellchecker to v2.11.3 I cannot start my app which requires node-spellchecker.

The error log is:

```
Error: A dynamic link library (DLL) initialization routine failed.
D:\workspace\typemark\node_modules\spellchecker\build\Release\spellchecker.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (D:\workspace\typemark\node_modules\spellchecker\lib\spellchecker.js:2:16)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
```

I have tried electron-rebuilt, also tried re-install io.js, electron and spellchecker, the error still happens. 

I met similar error on Mac ( ATOM_SHELL_ASAR.js throw error when require node-spellchcker) after I upgrade my electron these days. But I solved it by upgrade io.js to latest version.

On windows, however, I cannot solve this error. So I'm wondering if it is a bug, or anyone help me out ?

**Comment by kamesh-a** [comment]
We are facing this similar issue, I just came here to report,
Environment : 
Windows 8 64bit.
npm --version : 2.12.1
node/iojs --version :  2.3.4
process. versions : 
```
{ http_parser: '2.5.0',
  node: '2.3.4',
  v8: '4.2.77.20',
  uv: '1.6.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '44',
  openssl: '1.0.2d' }
```
But in node command prompt requiring spellchecker works. Not sure whether the binding dll bridge between module and atom is throwing error.

Please let us know, how can we avoid this and make spellchecker work.

**Comment by kamesh-a** [comment]
@abnerlee May i know which was your previous version iojs it worked in win8? if so did you downgrade and check to ensure it works in downgraded versions?

**Comment by abnerlee** [comment]
@kamesh-a  it used to work on io.js v1.x, with downgraded electron

**Comment by kamesh-a** [comment]
Anyone able to take a look into this, or instead of keeping this module nodejs package why cant we integrate it with ElECTRON and give api for use. so User can decide whether to use it or not.

Dictonary is mandtory for most application. in such it avoids recompiling and releasing with each builds. just my thoughts.

**Comment by abnerlee** [comment]
spellchecker seems working to me, after I read and follow instructions at <https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md> carefully.

**Comment by kamesh-a** [comment]
I thought to give a try once again cleaned all visual-studio version's , node js installation etc.
```
1. Do not install node.js as suggested by the node-installer into c:\program files. Install it in c:\nodejs. Everything in c:\program files requires special windows user rights. My feeling is that this is sometimes complicating matters, so do not go there.
2. Update npm globally to the most recent version: npm install npm --g
3. Try to install Visual Studio 2013 Update 4.
4. Use the latest python 2.7.9 version.
5. Try running npm install -g node-gyp --msvs_version=2013
6. npm install spellchecker

7. finally :
64bit : node-gyp rebuild --target=0.30.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell
32bit : node-gyp rebuild --target=0.30.2 --arch=ia32 --dist-url=https://atom.io/download/atom-shell

iojs version  - v0.2.3.4
```
Able to successfully rebuild. it works now.

**Comment by kamesh-a** [comment]
Due to iojs update to 3.1.0, Spellchecker compilation fails. current nan1.6.1 https://atom.io/download/atom-shell/nan-1.6.1.tgz is not suitable with it.

Compilation passes in < 3.0 versions of iojs.
