### ISSUE TITLE
On Mac OS X, calling setDictionary twice causes Electron app to segfault after Dictation / language events

### ISSUE THREAD

**Issue by bengotow** [atom/node-spellchecker#30]
A few of our users have reported that N1 (an Electron app) crashes in really strange scenarios:

- When you finish Mac OS X Dictation (activated by pressing fn-fn-fn).
- When you adjust anything in the System Preferences > Keyboard > Text (try changing Spelling from `US English` to `Australian English`.

I've been able to reproduce this in a tiny Electron app with nothing but these five lines of code run in the renderer process when the app opens:

```js
  checker = require('spellchecker');
  checker.setDictionary('en-US');
  console.log(checker.isMisspelled('allez-vous'));
  checker.setDictionary('fr');
  console.log(checker.isMisspelled('allez-vous'));
```

What's really interesting is that the scenarios above stop crashing the app if you remove the last two lines. It appears that calling setDictionary more than once causes something low level to be released twice, and downstream events that cause NSSpelling notifications cause `EXC_BAD_ACCESS`.

**Comment by zcbenz** [comment]
Fixed by #31.
