### ISSUE TITLE
When space is deleted before the wrong word it becomes unmarked

### ISSUE THREAD

**Issue by beshur** [atom/node-spellchecker#35]
Hi.

In the case when we have two spaces before the wrong word, and delete one of those spaces the word becomes unmarked (as if it became correct). Clicking on it triggers highlighting again.

**Comment by lee-dohm** [comment]
Is this a problem with the node-spellchecker npm module? Or is this a problem with Atom's spell-check package? According to the API in the [README](https://github.com/atom/node-spellchecker/blob/master/README.md), the only thing this module does is check individual words.

**Comment by beshur** [comment]
I confirm that the problem is with the **spellchecker** npm module.

**Comment by lee-dohm** [comment]
What is being sent to the spellchecker npm module that is causing this issue? Can you post an example snippet of code that reproduces the issue?

**Comment by beshur** [comment]
@lee-dohm, sorry can't share the code right now.
Spellchecker initialized with this:
```
webFrame.setSpellCheckProvider('en-US', true, {
        spellCheck: function(text) {
            return !(spellchecker.isMisspelled(text));
        }
    });
```
Nothing else regarding it.
Just try typing double space before the word with a mistake and then delete one of them.

**Comment by beshur** [comment]
Sorry, cannot provide live example for it now. 
Will reopen as soon as have an opportunity for that.
