### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by juh2** [atom/node-spellchecker#4]
From a discussion here (https://discuss.atom.io/t/spelling-in-english-only/11819) I guess that node-spellchecker does not support other languages beside en_US

Please add more languages.

**Comment by despairblue** [comment]
:+1:

**Comment by despairblue** [comment]
Could `webFrame.setSpellCheckProvider` in atom-shell be used for that?

**Comment by julien-noblet** [comment]
:+1:

**Comment by despairblue** [comment]
It seems @paulcbetts changes will solve this, see https://github.com/atom/node-spellchecker/pull/6 and https://github.com/atom/node-spellchecker/pull/7

Unless I misunderstood the PRs. I wonder if it also works on linux :worried:

**Comment by paulcbetts** [comment]
@despairblue It will work on Linux, but you've got to manage shipping the dictionaries yourself (or more likely, track down where on the system they're storing the Hunspell dictionaries)

**Comment by despairblue** [comment]
@paulcbetts awesome, that's still way better the status quo :clap:

**Comment by juh2** [comment]
hunspell -D shows that I use the german dictionary, but in Atom I still have the english dictionary only.

**Comment by Aprifel** [comment]
A support for other languages (e.g. German) would be great

**Comment by paulcbetts** [comment]
This is fixed in this package, now Atom needs to use the multi-language features that node-spellchecker exposes

**Comment by donlencho** [comment]
So is this being worked on in Atom to integrate it? I'm not sure I get what needs to be done for this to be usable. Thank you.

**Comment by Yaco** [comment]
:thumbsup:
