### ISSUE TITLE
Summarize changes in each release

### ISSUE THREAD

**Issue by bengotow** [atom/node-spellchecker#43]
Hey folks! Our team has been tracking down a breaking issue in N1 today and it turns out it's caused by the 3.3.0 release of node-spellchecker (mysteriously, it just causes the app to fall into a hard loop at launch. We haven't determined why yet.). Looking over the recent commits, it's really not clear what has changed or why—would be really great if we could start putting release notes on new versions to make triaging things easier. We'll be locking N1 to a specific release rather than `^3.2.1` to avoid these problems in the future, but it'd be great to keep up with changes.

**Comment by zcbenz** [comment]
How do people usually tracking the changes? Is adding a `CHANGELOG.md` enough?

**Comment by lee-dohm** [comment]
We have a tool that the Atom team uses to roll up all Pull Request information relevant for each release. Perhaps the Electron team should start using it as well? I'll bring it up in the next team meeting.
