### ISSUE TITLE
How to understand if Hunspell is used or native dictionary?

### ISSUE THREAD

**Issue by beshur** [atom/node-spellchecker#47]
Hi.

Is there a way to understand which spellcheck engine is used?

**Comment by lee-dohm** [comment]
There isn't currently a method in the API that surfaces this information.

Also, [we're trying to control the amount of Issues that we have to triage](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

If you're intending to request a feature be added, please see the [How Do I Write a (Good) Enhancement Suggestion](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion) section of the [Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) for suggestions and feel free to reopen the Issue.
