### ISSUE TITLE
Common contractions are marked as misspelled

### ISSUE THREAD

**Issue by CharlieHess** [atom/node-spellchecker#5]
We're using the `spellchecker` module within the `preload` script of a renderer process, and have followed the basic steps for setting it up as the provider via [`web-frame`](https://github.com/atom/atom-shell/blob/master/docs/api/web-frame.md).

However, it seems to break words at the apostrophe mark rather than process the complete contraction. I'm not sure if this is an issue with the dictionary or the affix file, but the result is undesirable:

![](https://s3.amazonaws.com/f.cl.ly/items/3Z0g2b2b221K2R0A412z/Image%202015-01-13%20at%203.01.06%20PM.png)

Any ideas on what's happening?

**Comment by kevinsawicki** [comment]
What platform is that screenshot from?

**Comment by CharlieHess** [comment]
That's on OS X.

**Comment by kevinsawicki** [comment]
Not sure how you are integrating but I'm not seeing the same results from the command line:

```
$ node
> s = require('./lib/spellchecker')
{ isMisspelled: [Function],
  getCorrectionsForMisspelling: [Function] }
> s.isMisspelled("doesn't")
false
> s.isMisspelled("would't")
false
```

Can you share the code of how you are calling it?

**Comment by CharlieHess** [comment]
``` coffeescript
global.spellChecker = require 'spellchecker'

...

require('web-frame').setSpellCheckProvider "en-US", false,
  spellCheck: (text) ->
    return true unless global.spellChecker?
    ret = not global.spellChecker.isMisspelled(text)
    logger.debug "Spell checking: #{text} returned: #{ret}"
    ret 
```
And the log file produces:
```
2015-01-13T23:16:20.701Z - debug: [main.coffee] - Spell checking: doesn returned: false
2015-01-13T23:16:20.707Z - debug: [main.coffee] - Spell checking: doesn returned: false
2015-01-13T23:16:22.702Z - debug: [main.coffee] - Spell checking: doesn returned: false
2015-01-13T23:16:22.706Z - debug: [main.coffee] - Spell checking: doesn returned: false
2015-01-13T23:16:28.142Z - debug: [main.coffee] - Spell checking: doesn't returned: true
```
So it's definitely getting the right result. But the input field in the renderer is out of sync.

**Comment by zcbenz** [comment]
@CharlieHess Can you move this issue to atom-shell? I believe it is a bug of how we handle contractions.

**Comment by CharlieHess** [comment]
@zcbenz Will do.

**Comment by kevinsawicki** [comment]
Closing this out here.
