### ISSUE TITLE
Error in ELECTRON_ASAR

### ISSUE THREAD

**Issue by WhiteTusk** [atom/node-spellchecker#65]
I get this error in Windows x64 in the ELECTRON_ASAR.js line 173:

Uncaught Error: %1 is not a valid Win32 application.
\\?\(path to my app)\node_modules\spellchecker\build\Release\spellchecker.node

This same code is working correctly in macOS (latest version). Any guess to what might be happening?

**Comment by MehediH** [comment]
Getting the  same error on  my machine too.

**Comment by neurosnap** [comment]
Any updates on this issue?  I'm getting the same exact error on windows.

**Comment by MehediH** [comment]
@neurosnap Try installing this first https://github.com/felixrieseberg/windows-build-tools and then do npm install, worked for me.

**Comment by neurosnap** [comment]
Yes, for anyone else looking at this, each electron target must be built on their target platform.  Windows must be built on windows, linux on linux, and mac on mac.

**Comment by 50Wliu** [comment]
Looks like this has been resolved.
