### ISSUE TITLE
Respect dictionary encoding

### ISSUE THREAD

**Issue by kolya-ay** [atom/node-spellchecker#89]
As soon as `node-spellchecker` tries to be as much system-native as possible, I think it makes sense to support *non UTF-8* encoded dictionaries. 

It seems that many distributions package their `hunspell-*` packages directly from [libreoffice repo](https://gerrit.libreoffice.org/gitweb?p=dictionaries.git;a=summary) (so [does Chrome](https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries/+/master) with its own additions). Unfortunately, the encodings in the repo [vary a lot](https://github.com/LibreOffice/dictionaries/issues/7). So to fully support [system dictionaries](https://github.com/atom/node-spellchecker/issues/51) we have to transcode strings. Probably, [this way](https://github.com/bartosz-antosik/vscode-spellright/issues/50#issuecomment-323578475).

Related to #51, #54

**Comment by dmoonfire** [comment]
This should be resolved by https://github.com/atom/node-spellchecker/pull/95.

**Comment by dmoonfire** [comment]
Since I haven't heard a response, I'm going to assume this is working. Feel free to reopen if it isn't.
