### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by cristianfraser** [atom/node-spellchecker#9]
I'm developing a nwjs app and wanted to use this module. Installing with `npm install spellchecker` logs this:

```
Cristians-MacBook-Pro-2:project cristian$ npm install spellchecker
|
> spellchecker@2.0.0 install /Users/cristian/project/node_modules/spellchecker
> node-gyp rebuild

  CXX(target) Release/obj.target/spellchecker/src/main.o
  CXX(target) Release/obj.target/spellchecker/src/spellchecker_mac.o
  SOLINK_MODULE(target) Release/spellchecker.node
  SOLINK_MODULE(target) Release/spellchecker.node: Finished
spellchecker@2.0.0 node_modules/spellchecker
└── nan@1.6.1
```

So I guess it's installed properly. But when I try using require('spellchecker') I get:

```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/cristian/project/node_modules/spellchecker/lib/spellchecker.js:1:78)
    at Module._compile (module.js:454:26)
    at Object.Module._extensions..js (module.js:472:10)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
```

I'm using
```
npm 2.4.1
node v0.10.33
```

**Comment by cristianfraser** [comment]
I built using node `v0.12` and it worked.

**Comment by abnerlee** [comment]
I met the same issue. I'm using node v0.10.32 npm v2.4.1 on OS X

**Comment by abnerlee** [comment]
Hi, I solved this by switching from node.js to io.js and then do npm install again. Hope this will help.

**Comment by astoilkov** [comment]
I have the same error and after I did that I started getting this error: `Uncaught Error: Module version mismatch. Expected 44, got 14.`

**Comment by maxbrunsfeld** [comment]
@astoilkov In your case, it looks like you're trying to use this module from Atom, but it is compiled to work with node.js. If you have an Atom package that uses this module, you should just need to run `apm rebuild` from the package directory.
