### ISSUE TITLE
License problem with Hunspell being GPL

### ISSUE THREAD

**Issue by ccnokes** [atom/node-spellchecker#96]
My organization has a policy against distributing code that is GPL licensed. Hunspell is GPL licensed which makes using this a no-go. Are there any alternative fallback spellchecking libraries that can be explored in place of Hunspell? Or is there some compiling magic that can be done to safely remove any dependencies on Hunspell, regardless of platform? 

Sorry if this is a stupid question -- just seeing if anything can be done here before I go and fork this and a library that depends on it just so I can pull Hunspell out.

**Comment by zcbenz** [comment]
Hunspell's homepage says it uses GPL/LGPL/MPL tri-license: http://hunspell.github.io.

**Comment by ccnokes** [comment]
Yes I know -- each of those licenses is similar and my organization has restrictions on distributing software that has libraries with any of those licenses. I'm no expert in the legalities of software licenses and I don't really want to get into that. I just know those licenses are problematic for my organization (and others as well because this stipulation is being driven by some customers). So I just thought I'd go out on a limb and seeing if anything can be done easily about it.

**Comment by dmoonfire** [comment]
@ccnokes: I would check about the LGPL license. The main thing about LGPL (as opposed to GPL) is that if you don't make modifications, it doesn't pull in the rest of the code.  Likewise, the Wikipedia site on [MPL](https://en.wikipedia.org/wiki/Mozilla_Public_License) says that it only applies to the code in the same file and can be linked to commercial software.

I know I went to my company's lawyers and they didn't have a problem with the latter two, just GPL.

**Comment by ccnokes** [comment]
Good to know @dmoonfire. I've already resolved this for my project by forking and removing hunspell. I tried talking reason to our legal person but they wouldn't really listen 🤷‍♂️. Hopefully what you said helps someone else though 👍.

**Comment by dmoonfire** [comment]
Since you've already handle it, I'm going to close this issue.
